/**
 * PDF Export — captures dashboard as a multi-page PDF with optional watermark.
 * Uses html2canvas-pro for rendering and jspdf for PDF creation.
 */

export async function exportDashboardPDF(
  elementId: string,
  filename: string,
  options?: { watermark?: string },
) {
  const element = document.getElementById(elementId);
  if (!element) return;

  // Dynamic imports to keep bundle size small
  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
    import('html2canvas-pro'),
    import('jspdf'),
  ]);

  // Hide no-print elements temporarily
  const noPrintEls = element.querySelectorAll('.no-print');
  noPrintEls.forEach((el) => ((el as HTMLElement).style.display = 'none'));

  // Capture at 2x for crisp text
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: '#FFFFFF',
  });

  // Restore hidden elements
  noPrintEls.forEach((el) => ((el as HTMLElement).style.display = ''));

  const imgWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  const pdf = new jsPDF('p', 'mm', 'a4');
  let heightLeft = imgHeight;
  let position = 0;

  // First page
  pdf.addImage(
    canvas.toDataURL('image/jpeg', 0.92),
    'JPEG',
    0,
    position,
    imgWidth,
    imgHeight,
  );
  heightLeft -= pageHeight;

  // Additional pages if content overflows
  while (heightLeft > 0) {
    position = -(imgHeight - heightLeft);
    pdf.addPage();
    pdf.addImage(
      canvas.toDataURL('image/jpeg', 0.92),
      'JPEG',
      0,
      position,
      imgWidth,
      imgHeight,
    );
    heightLeft -= pageHeight;
  }

  // Watermark on each page
  if (options?.watermark) {
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(36);
      pdf.setTextColor(200, 200, 200);
      pdf.saveGraphicsState();
      // Diagonal watermark
      const centerX = imgWidth / 2;
      const centerY = pageHeight / 2;
      pdf.text(options.watermark, centerX, centerY, {
        align: 'center',
        angle: 45,
      });
      pdf.restoreGraphicsState();
    }
  }

  // Footer on each page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by validator.vn — ${new Date().toLocaleDateString()}`,
      imgWidth / 2,
      pageHeight - 5,
      { align: 'center' },
    );
    pdf.text(`${i}/${totalPages}`, imgWidth - 10, pageHeight - 5, {
      align: 'right',
    });
  }

  pdf.save(`${filename}.pdf`);
}
